import Head from 'next/head'
import {Header} from 'src/Components/Header'
import {UserSettingMain} from 'src/Components/UserSettingMain'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="複利計算"/>

      <h1>計算入力</h1>
    </>
  )
}
